apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tutorial-pipeline-run-1
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: tutorial-pipeline
  resources:
  - name: source-repo
    resourceRef:
      name: nginx-sample-git
